---

- name: Reload dnsmasq
  ansible.builtin.systemd:
    state: restarted
    name: dnsmasq.service
    daemon_reload: yes
  ignore_errors: true

- name: Apply netplan configuration
  ansible.builtin.command:
    cmd: netplan apply
  ignore_errors: true