---
- name: Copy apt config for unifi
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/unifi.list
    src: unifi.list

- name: Copy apt key for unifi
  ansible.builtin.copy:
    dest: /etc/unifi.key
    src: unifi.key
  notify:
    - Trust unifi key

- name: Force handlers
  meta: flush_handlers

# - name: Install controller software
#   ansible.builtin.apt:
#     name:
#       - unifi
#     state: present
#     update_cache: true
#   notify:
#     - Unifi installed