---
- name: Disable password authentication for sshd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: PasswordAuthentication no
    regexp: "(?i)^\\s*PasswordAuthentication"
  notify:
    - Restart sshd

- name: Enable key authentication for sshd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: PubkeyAuthentication yes
    regexp: "(?i)^\\s*PubkeyAuthentication"
  notify:
    - Restart sshd
